import type { ChatMessagePayload, RESTPostChannelMessagesBody, MentionsPayload } from "@guildedjs/guilded-api-typings";
import type { Client } from "./Client";
import { Base } from "./Base";
import type { User } from "./User";
import type { Member } from "./Member";
import { buildMemberKey } from "../util";
import { Embed } from "./Embed";
import type { Channel } from "./channels";
import type { MessageContent } from "../typings";

export enum MessageType {
    Default,
    System,
}

export class Message extends Base<ChatMessagePayload> {
    /** The id of the message. */
    readonly id: string;
    /** The ID of the channel */
    readonly channelId: string;
    /** The ID of the server this message belongs to */
    readonly serverId: string | null;
    /** The type of chat message. "system" messages are generated by Guilded, while "default" messages are user or bot-generated. */
    readonly type: MessageType;
    /** The content of the message */
    content: string;
    /** The mentions within this message */
    mentions?: MentionsPayload;
    /** The ID of the messages that this is replying to. */
    readonly replyMessageIds: string[] = [];
    /** If set, this message will only be seen by those mentioned or replied to. */
    readonly isPrivate: boolean;
    /** If set, this message did not notify, mention or reply recipients. */
    readonly isSilent: boolean;
    /** The ID of the user who created this message (Note: If this event has createdByBotId or createdByWebhookId present, this field will still be populated, but can be ignored. In these cases, the value of this field will always be Ann6LewA) */
    readonly createdById: string;
    /** The ID of the bot who created this message, if it was created by a bot */
    readonly createdByBotId: string | null;
    /** The ID of the webhook who created this message, if it was created by a webhook */
    readonly createdByWebhookId: string | null;
    /** The timestamp that the message was created at. */
    readonly _createdAt: number;
    /** The timestamp that the message was updated at, if relevant */
    _updatedAt: number | null;
    /** Whether the message has been deleted */
    deleted = false;
    /** When the message was deleted, if it was */
    _deletedAt: number | null = null;

    constructor(client: Client, data: ChatMessagePayload) {
        super(client, data);

        this.id = data.id;
        this.channelId = data.channelId;
        this.content = data.content ?? "";
        this.serverId = data.serverId ?? null;
        this.replyMessageIds = data.replyMessageIds ?? [];
        this.createdById = data.createdBy;
        this.createdByBotId = data.createdByBotId ?? null;
        this.createdByWebhookId = data.createdByWebhookId ?? null;
        this._createdAt = Date.parse(data.createdAt);
        this._updatedAt = null;
        this.isPrivate = data.isPrivate ?? false;
        this.isSilent = data.isSilent ?? false;
        this.type = data.type === "system" ? MessageType.System : MessageType.Default;

        this._update(data);
    }

    get createdAt(): Date {
        return new Date(this._createdAt);
    }

    get updatedAt(): Date | null {
        return this._updatedAt ? new Date(this._updatedAt) : null;
    }

    get deletedAt(): Date | null {
        return this._deletedAt ? new Date(this._deletedAt) : null;
    }

    /** Update details of this structure */
    _update(data: Partial<ChatMessagePayload> | { deletedAt: string }): this {
        if ("content" in data && typeof data.content !== "undefined") {
            this.content = data.content;
        }

        if ("mentions" in data) {
            this.mentions = data.mentions;
        }

        if ("updatedAt" in data) {
            this._updatedAt = data.updatedAt ? Date.parse(data.updatedAt) : null;
        }

        if ("deletedAt" in data) {
            this.deleted = true;
            this._deletedAt = Date.parse(data.deletedAt);
        }

        return this;
    }

    /** Get the author of this message */
    get author(): User | null {
        return this.client.users.cache.get(this.createdById) ?? null;
    }

    /** The author id of the user who sent this message. */
    get authorId(): string {
        return this.createdByBotId ?? this.createdByWebhookId ?? this.createdById;
    }

    /** Get the member of this message (if in server) */
    get member(): Member | null {
        return this.serverId ? this.client.members.cache.get(buildMemberKey(this.serverId, this.authorId)) ?? null : null;
    }

    /** Get the channel of this message */
    get channel(): Channel | null {
        return this.client.channels.cache.get(this.channelId) ?? null;
    }

    /* Edit message content */
    edit(newContent: RESTPostChannelMessagesBody | Embed | string): Promise<Message> {
        return this.client.messages.update(this.channelId, this.id, newContent).then(() => this);
    }

    /** Send a message in the same channel as this message. */
    send(content: MessageContent) {
        return this.client.messages.send(this.channelId, content);
    }

    /** Send a message that replies to this message. It mentions the user who sent this message. */
    reply(content: MessageContent) {
        return this.client.messages.send(
            this.channelId,
            typeof content === "string"
                ? { content, replyMessageIds: [this.id] }
                : content instanceof Embed
                ? { embeds: [content] }
                : { ...content, replyMessageIds: content.replyMessageIds ? [this.id, ...content.replyMessageIds] : [this.id] },
        );
    }

    /** Add a reaction emote */
    addReaction(emoteId: number): Promise<void> {
        return this.client.rest.router.addReactionEmote(this.channelId, this.id, emoteId).then(() => void 0);
    }

    /** Delete a reaction emote */
    deleteReaction(emoteId: number): Promise<void> {
        return this.client.rest.router.deleteReactionEmote(this.channelId, this.id, emoteId).then(() => void 0);
    }

    /** Delete this message. */
    delete() {
        return this.client.messages.delete(this.channelId, this.id);
    }
}
